// Auto-generated by build_gallery.py — DO NOT EDIT MANUALLY
// Generated: 2026-04-12T23:02:49.425881
// Total: 21 images, 0 videos across 6 categories

var GALLERY_DATA = {
  "categories": [
    {
      "id": "gallery",
      "name": "Gallery"
    },
    {
      "id": "portrait",
      "name": "Portrait"
    },
    {
      "id": "wedding",
      "name": "Wedding"
    },
    {
      "id": "landscape",
      "name": "Landscape"
    },
    {
      "id": "drone",
      "name": "Drone"
    },
    {
      "id": "videography",
      "name": "Videography"
    }
  ],
  "images": {
    "gallery": [
      "img/gallery/gallery-1.jpg",
      "img/gallery/gallery-10.jpg",
      "img/gallery/gallery-11.jpg",
      "img/gallery/gallery-12.jpg",
      "img/gallery/gallery-13.jpg",
      "img/gallery/gallery-14.jpg",
      "img/gallery/gallery-15.jpg",
      "img/gallery/gallery-16.jpg",
      "img/gallery/gallery-17.jpg",
      "img/gallery/gallery-18.jpg",
      "img/gallery/gallery-19.jpg",
      "img/gallery/gallery-2.jpg",
      "img/gallery/gallery-21.jpg",
      "img/gallery/gallery-3.jpg",
      "img/gallery/gallery-4.jpg",
      "img/gallery/gallery-5.jpg",
      "img/gallery/gallery-6.jpg",
      "img/gallery/gallery-7.jpg",
      "img/gallery/gallery-8.jpg",
      "img/gallery/gallery-9.jpg",
      "img/gallery/shtdfh.jpg"
    ],
    "portrait": [],
    "wedding": [],
    "landscape": [],
    "drone": [],
    "videography": []
  },
  "videos": {}
};
