#!/usr/bin/env python3
"""
Gallery Data Builder for Dreamy Photography Atlanta
====================================================
Reads category.txt for categories, scans image folders, and generates gallery-data.js.

Usage:
    python build_gallery.py

This script:
  1. Reads category.txt for category folder names
  2. Scans img/<category>/ for image files (jpg, jpeg, png, gif, webp)
  3. Skips any file whose name starts with '_'
  4. Checks for video_link.txt in each folder
  5. Outputs js/gallery-data.js with all the data

Run this script whenever you add/remove images or categories.
"""

import os
import json
import re

# Paths relative to this script's location
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(SCRIPT_DIR, "category.txt")
IMG_DIR = os.path.join(SCRIPT_DIR, "img")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "js", "gallery-data.js")

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}


def read_config():
    """Read category names from category.txt."""
    categories = []
    if not os.path.exists(CONFIG_FILE):
        print(f"WARNING: {CONFIG_FILE} not found. Creating default config.")
        with open(CONFIG_FILE, "w") as f:
            f.write("# Gallery Categories\n# One folder name per line\ngallery\nportrait\nwedding\n")
        return ["gallery", "portrait", "wedding"]

    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                categories.append(line)

    return categories


def scan_images(folder_path, category_name):
    """Scan a folder for image files, skipping files starting with '_'."""
    images = []
    if not os.path.isdir(folder_path):
        return images

    for filename in sorted(os.listdir(folder_path)):
        # Skip files starting with '_'
        if filename.startswith("_"):
            continue
        # Skip directories
        filepath = os.path.join(folder_path, filename)
        if os.path.isdir(filepath):
            continue
        # Check extension
        _, ext = os.path.splitext(filename.lower())
        if ext in IMAGE_EXTENSIONS:
            # Use forward slashes for web paths
            web_path = f"img/{category_name}/{filename}"
            images.append(web_path)

    return images


def read_video_links(folder_path):
    """Read video_link.txt from a folder if it exists."""
    video_file = os.path.join(folder_path, "video_link.txt")
    videos = []
    if not os.path.exists(video_file):
        return videos

    with open(video_file, "r", encoding="utf-8") as f:
        content = f.read()

    # Split by comma or newline, clean up
    for item in re.split(r"[,\n]+", content):
        url = item.strip()
        if url and ("youtube" in url or "youtu.be" in url or "vimeo" in url):
            videos.append(url)

    return videos


def build_gallery_data():
    """Main build function."""
    categories = read_config()
    print(f"Categories in category.txt: {categories}")

    data = {
        "categories": [],
        "images": {},
        "videos": {}
    }

    total_images = 0
    total_videos = 0

    for cat in categories:
        folder_path = os.path.join(IMG_DIR, cat)
        display_name = cat.replace("_", " ").replace("-", " ").title()

        # Always add the category (even if folder is empty or doesn't exist)
        data["categories"].append({
            "id": cat,
            "name": display_name
        })

        if not os.path.isdir(folder_path):
            print(f"  {cat}: folder img/{cat}/ does not exist (category still shown)")
            data["images"][cat] = []
            continue

        # Scan images
        images = scan_images(folder_path, cat)
        # Read videos
        videos = read_video_links(folder_path)

        data["images"][cat] = images
        if videos:
            data["videos"][cat] = videos

        total_images += len(images)
        total_videos += len(videos)
        print(f"  {cat}: {len(images)} images, {len(videos)} videos")

    # Write output JS file
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    json_str = json.dumps(data, indent=2)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_gallery.py — DO NOT EDIT MANUALLY\n")
        f.write(f"// Generated: {__import__('datetime').datetime.now().isoformat()}\n")
        f.write(f"// Total: {total_images} images, {total_videos} videos across {len(data['categories'])} categories\n\n")
        f.write(f"var GALLERY_DATA = {json_str};\n")

    print(f"\nOutput written to: {OUTPUT_FILE}")
    print(f"Total: {total_images} images, {total_videos} videos, {len(data['categories'])} categories")


if __name__ == "__main__":
    build_gallery_data()
